project_id = "orgxcrnnecblhuxjfruy"

[auth]
# The base URL of your website. Used as an allow-list for redirects and for constructing URLs used
# in emails. Set this to your production URL.
site_url = "https://www.forcemajeure.vip"

# A list of *exact* URLs that auth providers are permitted to redirect to post authentication
additional_redirect_urls = [
  "https://www.forcemajeure.vip",
  "http://localhost:8080"
]

# How long email confirmation tokens are valid (in seconds). Default is 24 hours.
# email_confirm_expiry = 86400

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[functions.spotify-auth]
verify_jwt = false

[functions.generate-scavenger-tokens]
verify_jwt = false

[functions.validate-location]
verify_jwt = false

[functions.validate-scavenger-token]
verify_jwt = false

[functions.claim-scavenger-reward]
verify_jwt = true

[functions.create-checkout-session]
verify_jwt = true

[functions.handle-stripe-webhook]
verify_jwt = false