import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useTranslation } from 'react-i18next';
import { Ticket, BarChart3, ChevronRight } from 'lucide-react';
import { Card, CardContent } from '@/components/common/shadcn/card';
import { FmI18nCommon } from '@/components/common/i18n';
import { cn } from '@/shared';
import { GROUP_COLORS } from '../constants';
import { formatPrice, getTotalTicketsInGroup, getTotalRevenueInGroup, calculateTotalTickets, calculateTotalRevenue, calculateTotalGroups, calculateTotalTiers, } from '../utils';
export function OverviewView({ groups, onGroupClick }) {
    const { t } = useTranslation('common');
    const totalTickets = calculateTotalTickets(groups);
    const totalRevenue = calculateTotalRevenue(groups);
    const totalGroups = calculateTotalGroups(groups);
    const totalTiers = calculateTotalTiers(groups);
    return (_jsxs("div", { className: 'space-y-6', children: [_jsxs("div", { children: [_jsx(FmI18nCommon, { i18nKey: 'ticketGroupManager.ticketingOverview', as: 'h3', className: 'text-2xl font-semibold mb-2' }), _jsx(FmI18nCommon, { i18nKey: 'ticketGroupManager.ticketingOverviewDescription', as: 'p', className: 'text-muted-foreground' })] }), _jsxs("div", { className: 'grid grid-cols-4 gap-4', children: [_jsx(Card, { children: _jsx(CardContent, { className: 'pt-6', children: _jsxs("div", { className: 'text-center', children: [_jsx(Ticket, { className: 'h-8 w-8 mx-auto mb-2 text-fm-gold' }), _jsx("div", { className: 'text-2xl font-bold', children: totalTickets.toLocaleString() }), _jsx(FmI18nCommon, { i18nKey: 'ticketGroupManager.totalTickets', as: 'div', className: 'text-xs text-muted-foreground' })] }) }) }), _jsx(Card, { children: _jsx(CardContent, { className: 'pt-6', children: _jsxs("div", { className: 'text-center', children: [_jsx(BarChart3, { className: 'h-8 w-8 mx-auto mb-2 text-fm-gold' }), _jsx("div", { className: 'text-2xl font-bold', children: formatPrice(totalRevenue) }), _jsx(FmI18nCommon, { i18nKey: 'ticketGroupManager.potentialRevenue', as: 'div', className: 'text-xs text-muted-foreground' })] }) }) }), _jsx(Card, { children: _jsx(CardContent, { className: 'pt-6', children: _jsxs("div", { className: 'text-center', children: [_jsx("div", { className: 'h-8 w-8 mx-auto mb-2 rounded-full bg-fm-gold/20 flex items-center justify-center', children: _jsx("span", { className: 'text-lg font-bold text-fm-gold', children: totalGroups }) }), _jsx("div", { className: 'text-2xl font-bold', children: totalGroups }), _jsx(FmI18nCommon, { i18nKey: 'ticketGroupManager.ticketGroups', as: 'div', className: 'text-xs text-muted-foreground' })] }) }) }), _jsx(Card, { children: _jsx(CardContent, { className: 'pt-6', children: _jsxs("div", { className: 'text-center', children: [_jsx("div", { className: 'h-8 w-8 mx-auto mb-2 rounded-full bg-fm-gold/20 flex items-center justify-center', children: _jsx("span", { className: 'text-lg font-bold text-fm-gold', children: totalTiers }) }), _jsx("div", { className: 'text-2xl font-bold', children: totalTiers }), _jsx(FmI18nCommon, { i18nKey: 'ticketGroupManager.totalTiers', as: 'div', className: 'text-xs text-muted-foreground' })] }) }) })] }), _jsxs("div", { children: [_jsx(FmI18nCommon, { i18nKey: 'ticketGroupManager.groupSummaries', as: 'h4', className: 'text-lg font-semibold mb-4' }), _jsxs("div", { className: 'space-y-3', children: [groups.map((group, index) => {
                                const groupTickets = getTotalTicketsInGroup(group);
                                const groupRevenue = getTotalRevenueInGroup(group);
                                const colorConfig = GROUP_COLORS.find(c => c.value === group.color) ||
                                    GROUP_COLORS[0];
                                return (_jsx(Card, { className: cn('border-2 cursor-pointer hover:shadow-md transition-all', colorConfig.value), onClick: () => onGroupClick(group.id), children: _jsx(CardContent, { className: 'p-4', children: _jsxs("div", { className: 'flex items-center justify-between', children: [_jsxs("div", { className: 'flex-1', children: [_jsxs("div", { className: 'flex items-center gap-3 mb-2', children: [_jsx("div", { className: cn('w-3 h-3 rounded-full', colorConfig.value) }), _jsx("h5", { className: 'font-semibold', children: group.name || t('ticketGroupManager.defaultGroupName', { number: index + 1 }) }), group.description && (_jsxs("span", { className: 'text-sm text-muted-foreground', children: ["\u2022 ", group.description] }))] }), _jsxs("div", { className: 'flex items-center gap-6 text-sm text-muted-foreground ml-6', children: [_jsx("span", { children: t('ticketGroupManager.tiersCount', { count: group.tiers.length }) }), _jsx("span", { children: "\u2022" }), _jsx("span", { children: t('ticketGroupManager.ticketsCount', { count: groupTickets }) }), _jsx("span", { children: "\u2022" }), _jsx("span", { className: 'text-fm-gold font-semibold', children: formatPrice(groupRevenue) })] })] }), _jsx(ChevronRight, { className: 'h-5 w-5 text-muted-foreground' })] }) }) }, group.id));
                            }), groups.length === 0 && (_jsxs("div", { className: 'text-center py-12 text-muted-foreground', children: [_jsx(Ticket, { className: 'h-12 w-12 mx-auto mb-3 opacity-50' }), _jsx(FmI18nCommon, { i18nKey: 'ticketGroupManager.noGroupsYet', as: 'p' })] }))] })] })] }));
}
