import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Calendar, Settings, ArrowLeft, Music2, MapPin, Clock, Mic2, } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { useTranslation } from 'react-i18next';
import { FmCommonUserPhoto } from '@/components/common/display/FmCommonUserPhoto';
import { FmCommonButton } from '@/components/common/buttons/FmCommonButton';
import { FmCommonInfoCard } from '@/components/common/display/FmCommonInfoCard';
import { Card, CardContent } from '@/components/common/shadcn/card';
import { Tabs, TabsContent, TabsList, TabsTrigger, } from '@/components/common/shadcn/tabs';
import { Badge } from '@/components/common/shadcn/badge';
import { UserArtistTab } from '@/components/profile/UserArtistTab';
import { FmI18nCommon } from '@/components/common/i18n';
export const DesktopProfileLayout = ({ user, profile, upcomingShows, loadingShows, hasLinkedArtist, loadingArtist, createdAt, }) => {
    const navigate = useNavigate();
    const { t } = useTranslation('common');
    return (_jsxs("div", { className: 'max-w-6xl mx-auto px-4 py-12 space-y-8', children: [_jsx("div", { className: 'flex items-center justify-between', children: _jsx(FmCommonButton, { variant: 'secondary', size: 'sm', onClick: () => navigate('/'), icon: ArrowLeft, className: 'text-muted-foreground hover:text-foreground', children: t('profile.backToEvents') }) }), _jsx(Card, { className: 'border-border/30 bg-card/20 backdrop-blur-lg relative', children: _jsx(CardContent, { className: 'p-0', children: _jsxs("div", { className: 'grid grid-cols-[400px_1fr] gap-0', children: [_jsxs("div", { className: 'relative h-full min-h-[600px]', children: [_jsx("div", { className: 'absolute top-4 left-4 z-10', children: _jsx(FmCommonButton, { variant: 'default', size: 'sm', onClick: () => navigate('/profile/edit'), icon: Settings, className: 'bg-background/80 backdrop-blur-sm', children: t('profile.editProfile') }) }), _jsx(FmCommonUserPhoto, { src: profile?.avatar_url, name: profile?.display_name || user.email, size: 'square', useAnimatedGradient: !profile?.avatar_url, className: 'rounded-l-md' })] }), _jsxs("div", { className: 'p-8 space-y-6', children: [_jsxs("div", { children: [_jsx("h2", { className: 'text-3xl font-canela font-medium text-foreground', children: profile?.display_name || t('profile.defaultName') }), _jsx(FmI18nCommon, { i18nKey: 'profile.memberTitle', as: 'p', className: 'text-sm text-muted-foreground mt-1' })] }), _jsxs(Tabs, { defaultValue: 'upcoming', className: 'w-full', children: [_jsxs(TabsList, { className: `grid w-full ${hasLinkedArtist ? 'grid-cols-3' : 'grid-cols-2'}`, children: [_jsx(TabsTrigger, { value: 'upcoming', children: t('profile.upcomingShows') }), hasLinkedArtist && (_jsxs(TabsTrigger, { value: 'artist', className: 'flex items-center gap-1', children: [loadingArtist ? (_jsx("div", { className: 'h-3 w-3 border-2 border-fm-gold/30 border-t-fm-gold rounded-full animate-spin' })) : (_jsx(Mic2, { className: 'h-3 w-3' })), t('profile.artist')] })), _jsx(TabsTrigger, { value: 'account', children: t('profile.account') })] }), hasLinkedArtist && (_jsx(TabsContent, { value: 'artist', className: 'mt-6', children: _jsx(UserArtistTab, {}) })), _jsx(TabsContent, { value: 'upcoming', className: 'space-y-4 mt-6', children: loadingShows ? (_jsx(FmI18nCommon, { i18nKey: 'profile.loadingShows', as: 'div', className: 'text-center py-8 text-muted-foreground' })) : upcomingShows.length === 0 ? (_jsxs("div", { className: 'text-center py-12', children: [_jsx(Music2, { className: 'h-12 w-12 text-muted-foreground mx-auto mb-4' }), _jsx(FmI18nCommon, { i18nKey: 'profile.noUpcomingShows', as: 'p', className: 'text-muted-foreground mb-4' }), _jsx(FmCommonButton, { variant: 'gold', size: 'sm', onClick: () => navigate('/'), children: t('profile.browseEvents') })] })) : (_jsx("div", { className: 'space-y-3', children: upcomingShows.map(event => {
                                                        const eventDate = new Date(event.date);
                                                        const formattedDate = eventDate.toLocaleDateString('en-US', {
                                                            weekday: 'short',
                                                            month: 'short',
                                                            day: 'numeric',
                                                            year: 'numeric',
                                                        });
                                                        const formattedTime = eventDate.toLocaleTimeString('en-US', {
                                                            hour: 'numeric',
                                                            minute: '2-digit',
                                                        });
                                                        return (_jsx(Card, { className: 'border-border/30 bg-card/10 backdrop-blur-sm hover:bg-card/20 transition-colors cursor-pointer', onClick: () => navigate(`/events/${event.id}`), children: _jsx(CardContent, { className: 'p-4', children: _jsxs("div", { className: 'flex gap-4', children: [_jsx("div", { className: 'w-20 h-20 rounded-md overflow-hidden bg-muted flex-shrink-0', children: event.cover_image_url ? (_jsx("img", { src: event.cover_image_url, alt: event.title, className: 'w-full h-full object-cover' })) : (_jsx("div", { className: 'w-full h-full bg-gradient-gold flex items-center justify-center', children: _jsx(Music2, { className: 'h-8 w-8 text-black' }) })) }), _jsxs("div", { className: 'flex-1 min-w-0', children: [_jsx("h3", { className: 'font-canela font-medium text-foreground mb-1 truncate', children: event.title }), _jsxs("div", { className: 'space-y-1', children: [_jsxs("div", { className: 'flex items-center gap-1.5 text-xs text-muted-foreground', children: [_jsx(Clock, { className: 'h-3 w-3' }), _jsxs("span", { children: [formattedDate, " at ", formattedTime] })] }), _jsxs("div", { className: 'flex items-center gap-1.5 text-xs text-muted-foreground', children: [_jsx(MapPin, { className: 'h-3 w-3' }), _jsx("span", { className: 'truncate', children: event.location })] })] }), _jsx("div", { className: 'mt-2', children: _jsx(Badge, { variant: 'outline', className: 'text-xs', children: t('profile.ticketCount', { count: event.ticket_count }) }) })] })] }) }) }, event.id));
                                                    }) })) }), _jsx(TabsContent, { value: 'account', className: 'space-y-4 mt-6', children: _jsx("div", { className: 'grid gap-4', children: _jsx(FmCommonInfoCard, { icon: Calendar, label: t('profile.memberSince'), value: createdAt, size: 'sm', iconClassName: 'text-fm-gold' }) }) })] })] })] }) }) })] }));
};
