import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Calendar, Settings, ArrowLeft, Music2, MapPin, Clock, Mic2, } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { useTranslation } from 'react-i18next';
import { FmCommonUserPhoto } from '@/components/common/display/FmCommonUserPhoto';
import { FmCommonButton } from '@/components/common/buttons/FmCommonButton';
import { FmCommonInfoCard } from '@/components/common/display/FmCommonInfoCard';
import { Card, CardContent } from '@/components/common/shadcn/card';
import { Tabs, TabsContent, TabsList, TabsTrigger, } from '@/components/common/shadcn/tabs';
import { Badge } from '@/components/common/shadcn/badge';
import { UserArtistTab } from '@/components/profile/UserArtistTab';
import { FmI18nCommon } from '@/components/common/i18n';
export const MobileProfileLayout = ({ user, profile, upcomingShows, loadingShows, hasLinkedArtist, loadingArtist, createdAt, }) => {
    const navigate = useNavigate();
    const { t } = useTranslation('common');
    return (_jsxs("div", { className: 'h-[calc(100vh-64px)] flex flex-col overflow-hidden', children: [_jsxs("div", { className: 'flex-shrink-0 px-4 pt-4 pb-2 space-y-4', children: [_jsxs("div", { className: 'flex items-center justify-between', children: [_jsx(FmCommonButton, { variant: 'secondary', size: 'sm', onClick: () => navigate('/'), icon: ArrowLeft, className: 'text-muted-foreground hover:text-foreground', children: t('profile.back') }), _jsx(FmCommonButton, { variant: 'default', size: 'sm', onClick: () => navigate('/profile/edit'), icon: Settings, className: 'bg-background/80 backdrop-blur-sm', children: t('profile.edit') })] }), _jsxs("div", { className: 'flex items-center gap-4', children: [_jsx(FmCommonUserPhoto, { src: profile?.avatar_url, name: profile?.display_name || user.email, size: 'xl', useAnimatedGradient: !profile?.avatar_url, className: 'flex-shrink-0' }), _jsxs("div", { className: 'min-w-0', children: [_jsx("h2", { className: 'text-xl font-canela font-medium text-foreground truncate', children: profile?.display_name || t('profile.defaultName') }), _jsx(FmI18nCommon, { i18nKey: 'profile.memberTitle', as: 'p', className: 'text-xs text-muted-foreground' })] })] })] }), _jsxs(Tabs, { defaultValue: 'upcoming', className: 'flex-1 flex flex-col overflow-hidden px-4', children: [_jsxs(TabsList, { className: `grid w-full flex-shrink-0 ${hasLinkedArtist ? 'grid-cols-3' : 'grid-cols-2'}`, children: [_jsx(TabsTrigger, { value: 'upcoming', children: t('profile.shows') }), hasLinkedArtist && (_jsxs(TabsTrigger, { value: 'artist', className: 'flex items-center gap-1', children: [loadingArtist ? (_jsx("div", { className: 'h-3 w-3 border-2 border-fm-gold/30 border-t-fm-gold rounded-full animate-spin' })) : (_jsx(Mic2, { className: 'h-3 w-3' })), t('profile.artist')] })), _jsx(TabsTrigger, { value: 'account', children: t('profile.account') })] }), _jsxs("div", { className: 'flex-1 overflow-y-auto mt-4 pb-4', children: [hasLinkedArtist && (_jsx(TabsContent, { value: 'artist', className: 'mt-0 h-full', children: _jsx(UserArtistTab, {}) })), _jsx(TabsContent, { value: 'upcoming', className: 'space-y-3 mt-0', children: loadingShows ? (_jsx(FmI18nCommon, { i18nKey: 'profile.loadingShows', as: 'div', className: 'text-center py-8 text-muted-foreground' })) : upcomingShows.length === 0 ? (_jsxs("div", { className: 'text-center py-8', children: [_jsx(Music2, { className: 'h-10 w-10 text-muted-foreground mx-auto mb-3' }), _jsx(FmI18nCommon, { i18nKey: 'profile.noUpcomingShows', as: 'p', className: 'text-muted-foreground text-sm mb-3' }), _jsx(FmCommonButton, { variant: 'gold', size: 'sm', onClick: () => navigate('/'), children: t('profile.browseEvents') })] })) : (_jsx("div", { className: 'space-y-2', children: upcomingShows.map(event => {
                                        const eventDate = new Date(event.date);
                                        const formattedDate = eventDate.toLocaleDateString('en-US', {
                                            weekday: 'short',
                                            month: 'short',
                                            day: 'numeric',
                                        });
                                        const formattedTime = eventDate.toLocaleTimeString('en-US', {
                                            hour: 'numeric',
                                            minute: '2-digit',
                                        });
                                        return (_jsx(Card, { className: 'border-border/30 bg-card/10 backdrop-blur-sm hover:bg-card/20 transition-colors cursor-pointer', onClick: () => navigate(`/events/${event.id}`), children: _jsx(CardContent, { className: 'p-3', children: _jsxs("div", { className: 'flex gap-3', children: [_jsx("div", { className: 'w-16 h-16 rounded-md overflow-hidden bg-muted flex-shrink-0', children: event.cover_image_url ? (_jsx("img", { src: event.cover_image_url, alt: event.title, className: 'w-full h-full object-cover' })) : (_jsx("div", { className: 'w-full h-full bg-gradient-gold flex items-center justify-center', children: _jsx(Music2, { className: 'h-6 w-6 text-black' }) })) }), _jsxs("div", { className: 'flex-1 min-w-0', children: [_jsx("h3", { className: 'font-canela font-medium text-foreground text-sm truncate', children: event.title }), _jsxs("div", { className: 'space-y-0.5 mt-1', children: [_jsxs("div", { className: 'flex items-center gap-1.5 text-xs text-muted-foreground', children: [_jsx(Clock, { className: 'h-3 w-3' }), _jsxs("span", { children: [formattedDate, " \u00B7 ", formattedTime] })] }), _jsxs("div", { className: 'flex items-center gap-1.5 text-xs text-muted-foreground', children: [_jsx(MapPin, { className: 'h-3 w-3' }), _jsx("span", { className: 'truncate', children: event.location })] })] }), _jsx(Badge, { variant: 'outline', className: 'text-[10px] mt-1 px-1.5 py-0', children: t('profile.ticketCount', { count: event.ticket_count }) })] })] }) }) }, event.id));
                                    }) })) }), _jsx(TabsContent, { value: 'account', className: 'space-y-3 mt-0', children: _jsx(FmCommonInfoCard, { icon: Calendar, label: t('profile.memberSince'), value: createdAt, size: 'sm', iconClassName: 'text-fm-gold' }) })] })] })] }));
};
