import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Settings } from 'lucide-react';
import { FmCommonModal } from './FmCommonModal';
import { FmCommonButton } from '@/components/common/buttons/FmCommonButton';
import { FmCommonBadgeGroup } from '@/components/common/display/FmCommonBadgeGroup';
import { DialogTitle } from '@/components/common/shadcn/dialog';
import { cn } from '@/shared';
export const FmResourceDetailsModal = ({ open, onOpenChange, title, eyebrow, imageUrl, metadata, badges, footer, children, className, layout = 'hero', canManage = false, onManage, imageAspectRatio = 'aspect-[3/4]', imagePlaceholder = true, actions, }) => {
    const showManage = canManage && onManage;
    // Manage button styled to sit in top-right, left of the close X button
    const manageButton = showManage ? (_jsx(FmCommonButton, { size: 'sm', variant: 'secondary', icon: Settings, onClick: onManage, className: 'absolute right-12 top-4 bg-white/10 text-white hover:bg-white/20 border border-white/30 px-3 py-1 h-7 text-xs', children: "Manage" })) : null;
    // Hero layout - full-width image at top
    if (layout === 'hero') {
        return (_jsxs(FmCommonModal, { open: open, onOpenChange: onOpenChange, title: '', headerContent: _jsx(DialogTitle, { className: 'sr-only', children: title }), className: cn('max-w-3xl p-0 overflow-hidden', className), children: [manageButton, imageUrl && (_jsxs("div", { className: 'w-full h-64 overflow-hidden relative', children: [_jsx("img", { src: imageUrl, alt: title, className: 'w-full h-full object-cover' }), _jsx("div", { className: 'absolute inset-0 bg-gradient-to-t from-background/90 via-background/40 to-transparent' })] })), _jsxs("div", { className: 'p-8 flex flex-col gap-6', children: [eyebrow && (_jsxs("div", { className: 'space-y-3', children: [_jsx("p", { className: 'text-[10px] uppercase tracking-[0.35em] text-white/50', children: eyebrow }), _jsx("h2", { className: 'text-3xl font-canela font-semibold text-white leading-tight', children: title })] })), metadata && metadata.length > 0 && (_jsx("div", { className: 'flex flex-col gap-2', children: metadata.map((item, index) => (_jsxs("div", { className: 'flex items-start gap-3 text-sm text-white/70', children: [item.icon && _jsx("span", { className: 'flex-shrink-0 mt-0.5 text-fm-gold', children: item.icon }), _jsx("span", { children: item.value })] }, `${item.label}-${index}`))) })), children && (_jsx("div", { className: cn('prose prose-invert max-w-none text-sm text-white/80 leading-relaxed', !children && 'italic text-white/60'), children: children })), badges && badges.length > 0 && (_jsx(FmCommonBadgeGroup, { badges: badges, badgeClassName: 'border-fm-gold/60 bg-fm-gold/10 text-fm-gold', gap: 'lg' })), actions && (_jsx("div", { className: 'flex flex-wrap gap-3', children: actions }))] }), footer && _jsx("div", { className: 'px-8 pb-8', children: footer })] }));
    }
    // Side-by-side layout - image on left, content on right
    return (_jsxs(FmCommonModal, { open: open, onOpenChange: onOpenChange, title: '', headerContent: _jsx(DialogTitle, { className: 'sr-only', children: title }), className: cn('max-w-3xl', className), children: [manageButton, _jsxs("div", { className: 'flex flex-col gap-8 sm:flex-row sm:items-stretch', children: [_jsxs("div", { className: 'sm:w-60 flex-shrink-0', children: [_jsxs("div", { className: 'space-y-3', children: [eyebrow && (_jsx("p", { className: 'text-[10px] uppercase tracking-[0.35em] text-white/50', children: eyebrow })), _jsx("h2", { className: 'text-3xl font-canela font-semibold text-white leading-tight', children: title })] }), _jsx("div", { className: 'mt-4 overflow-hidden rounded-xl border border-white/15 bg-white/5 shadow-inner', children: imageUrl ? (
                                // eslint-disable-next-line @next/next/no-img-element
                                _jsx("img", { src: imageUrl, alt: title, className: cn(imageAspectRatio, 'w-full object-cover') })) : imagePlaceholder ? (_jsx("div", { className: cn(imageAspectRatio, 'w-full bg-gradient-to-br from-fm-gold/15 via-fm-gold/5 to-transparent') })) : null })] }), _jsxs("div", { className: 'flex-1 flex flex-col justify-center gap-6 sm:min-h-[320px]', children: [metadata && metadata.length > 0 && (_jsx("dl", { className: 'grid grid-cols-1 gap-4 sm:grid-cols-2', children: metadata.map((item, index) => (_jsxs("div", { className: 'space-y-1', children: [_jsx("dt", { className: 'text-xs uppercase tracking-[0.3em] text-white/50', children: item.label }), _jsxs("dd", { className: 'text-sm text-white/90 flex items-center gap-2', children: [item.icon, item.value] })] }, `${item.label}-${index}`))) })), children && (_jsx("div", { className: cn('prose prose-invert max-w-none text-sm text-white/80 leading-relaxed', !children && 'italic text-white/60'), children: children })), badges && badges.length > 0 && (_jsx(FmCommonBadgeGroup, { badges: badges, className: 'mt-auto', badgeClassName: 'border-fm-gold/60 bg-fm-gold/10 text-fm-gold', gap: 'lg' })), actions && (_jsx("div", { className: 'flex flex-wrap gap-3', children: actions }))] })] }), footer && _jsx("div", { className: 'mt-6', children: footer })] }));
};
