// ============================================================================
// API - Supabase
// ============================================================================
// Re-export from the autogenerated client (single source of truth)
export { supabase } from '@/integrations/supabase/client';

export type {
  Database,
  Tables,
  TablesInsert,
  TablesUpdate,
  Enums,
  Json,
  CompositeTypes,
  Constants
} from './api/supabase/types';

// API - Queries (React Query hooks)
export * from './api/queries';

// ============================================================================
// Types - Feature types
// ============================================================================
// Event types - canonical source is features/events/types
export * from '../features/events/types';
// Ticketing types - extends event types with checkout/cart types
export * from './types/features/ticketing';
export * from './types/features/products';
export * from './types/features/payments';
export * from './types/features/activity-logs';
export * from './types/features/raveFamily';
export * from './types/features/groups';

// Artists exports - explicitly re-export to resolve conflict with events.ts
export type {
  Artist,
  ArtistWithGenres,
  ArtistSummary,
  ArtistFormData,
  ArtistSearchCriteria,
  ArtistRow,
  ArtistGenre,
  ArtistGenreRow,
  ArtistGenreWithDetails,
  Genre,
  GenreRow,
  GenreWithParent,
  GenreHierarchyNode
} from './types/features/artists';
export {
  isArtistWithGenres,
  artistFromRow,
  artistGenreFromRow,
  genreFromRow,
  getPrimaryGenre
} from './types/features/artists';

// Types - Other
export * from './types/imageAnchor';

// Deletion request types
export * from './types/deletionRequests';

// ============================================================================
// Stores
// ============================================================================
export * from './stores/cartStore';
export * from './stores/rolesStore';
export * from './stores/mockPaymentStore';

// ============================================================================
// Auth
// ============================================================================
export * from './auth/permissions';

// ============================================================================
// Config
// ============================================================================
export * from './config/featureFlags';

// ============================================================================
// Adapters
// ============================================================================
export {
  webStorage,
  storage,
  createTypedStorage,
  webSecureStorage,
  type StorageAdapter,
  type SecureStorageAdapter
} from './adapters/storage';

// ============================================================================
// Constants
// ============================================================================
export * from './constants/scrollThresholds';
export * from './constants/socialLinks';
export * from './constants/ticketLinks';
export * from './constants/timeConstants';

// Design System constants
export {
  COLORS,
  COLOR_CLASSES,
  SPACING,
  SPACING_VALUES,
  SPACING_CLASSES,
  TYPOGRAPHY,
  TEXT_RULES,
  DEPTH,
  BORDER_RADIUS,
  DESIGN_ELEMENTS,
  NAMING,
  PRIMARY_COMPONENTS,
  ICON_BUTTONS,
  INPUT_STYLES,
  LABEL_STYLES,
  LIST_ITEM_STYLES,
  A11Y,
  CONTENT_WIDTH,
  type ColorKey,
  type SpacingKey,
  type DepthLevel,
  type PrimaryComponent,
  type ContentWidth,
} from './constants/designSystem';

// ============================================================================
// Design tokens
// ============================================================================
export {
  FM_COLORS,
  FM_SPACING,
  FM_SPACING_PX,
  FM_FONTS,
  FM_FONT_WEIGHTS,
  FM_FONT_SIZES,
  FM_LINE_HEIGHTS,
  FM_RADII,
  FM_BORDER_WIDTHS,
  FM_SHADOWS,
  FM_DURATIONS,
  FM_EASINGS,
  FM_Z_INDEX,
  FM_DEPTH,
  FM_BREAKPOINTS,
  getColor,
  getSpacing,
  getSpacingPx,
  type FMColor,
  type FMSpacing,
  type FMFontSize,
  type FMFontWeight,
  type FMRadius,
  type FMShadow,
  type FMDuration,
  type FMZIndex,
  type FMDepthLevel,
  type FMBreakpoint
} from './design/tokens';

// ============================================================================
// Utils
// ============================================================================
// Core utils
export { cn } from './utils/utils';
export { logApiError, logApi } from './utils/apiLogger';
export { getImageUrl, compressImage, type ImageCompressionOptions } from './utils/imageUtils';

// Form validation
export {
  stringRequired,
  stringOptional,
  emailField,
  passwordField,
  urlField,
  urlOptional,
  phoneField,
  dateField,
  futureDateField,
  pastDateField,
  priceField,
  positiveNumber,
  contactFormSchema,
  eventFormSchema,
  profileFormSchema,
  sanitizeInput,
  encodeForUrl,
  prepareFormData,
  createFileValidation,
  passwordConfirmation,
} from './utils/formValidation';

// Time utils
export { formatTimeDisplay, parseTimeToMinutes } from './utils/timeUtils';

// Queue utils
export * from './utils/queueUtils';

// Session persistence
export { sessionPersistence } from './utils/sessionPersistence';

// Scavenger API
export { claimScavengerReward, type ClaimResult } from './utils/scavengerApi';

// Style utils
export * from './utils/styleUtils';

// Feature flag utils
export * from './utils/featureFlagOverrides';
export { formatFlagName, getFlagIcon, getFlagDescription } from './utils/featureFlagUtils';

// Environment utils
export {
  getEnvironment,
  isDevelopment,
  isProduction,
  getFeatureFlagEnvironment,
  getEnvironmentOverride,
  ENVIRONMENT_LABELS,
  type Environment,
  type FeatureFlagEnvironment
} from './utils/environment';

// ============================================================================
// Services
// ============================================================================
export { logger } from './services/logger';
export * from './services/eventViewsService';

// Error handling
export {
  handleError,
  withErrorHandler,
  withErrorHandlerSync,
} from './services/errorHandler';

// Environment service
export {
  environmentService,
  getCurrentEnvironmentName,
  getCurrentEnvironment,
  getAvailableEnvironments,
  isProduction as isProductionEnv,
  isDevelopment as isDevelopmentEnv,
  isQA,
} from './services/environmentService';

// Service factory
export { createService } from './services/createService';
export type { ServiceConfig } from './services/createService';

// Image upload service
export { imageUploadService } from './services/imageUploadService';

// Role management service
export { RoleManagementService } from './services/roleManagementService';

// ============================================================================
// Hooks
// ============================================================================
export { useToast } from './hooks/use-toast';
export { useIsMobile } from './hooks/use-mobile';
export { useFeatureFlags, useFeatureFlagHelpers } from './hooks/useFeatureFlags';
export { useFontLoader } from './hooks/useFontLoader';
export { useFontLoaded, useCanelaLoaded, useScreamerLoaded } from './hooks/useFontLoaded';
export { useProxyToken } from './hooks/useProxyToken';
export { useUserRole, useUserPermissions } from './hooks/useUserRole';
export { useDebounce } from './hooks/useDebounce';
export {
  useCurrentEnvironment,
  useAvailableEnvironments,
  useEnvironmentName,
  useIsProduction,
  useIsDevelopment,
  useIsQA,
} from './hooks/useEnvironment';
export {
  useAsyncMutation,
  useAsyncMutationSimple,
  type UseAsyncMutationOptions,
  type UseAsyncMutationReturn,
} from './hooks/useAsyncMutation';
/** @deprecated Use useAsyncMutation instead */
export { useAsyncAction, type UseAsyncActionOptions } from './hooks/useAsyncAction';
export { useAsyncOperation, type UseAsyncOperationReturn } from './hooks/useAsyncOperation';
export {
  useDeleteConfirmation,
  type UseDeleteConfirmationOptions,
  type UseDeleteConfirmationReturn,
} from './hooks/useDeleteConfirmation';
export { useDateTimePicker } from './hooks/useDateTimePicker';
export { useScrollPosition } from './hooks/useScrollPosition';
export { useScrollSnap } from './hooks/useScrollSnap';
export { useRecentSelections } from './hooks/useRecentSelections';
export { useEventViews } from './hooks/useEventViews';
export { useCreateEntityNavigation } from './hooks/useCreatedEntityReturn';
export { useModalState, type UseModalStateReturn } from './hooks/useModalState';
export { useLocalStorage } from './hooks/useLocalStorage';

// Shopping Cart
export { ShoppingCartProvider, useShoppingCart } from './hooks/useShoppingCart';

// Fuzzy search
export {
  useFuzzySearch,
  fuzzySearchKeys,
  type FuzzySearchConfig,
  type FuzzySearchResults,
  type UseFuzzySearchReturn,
  type SearchableTable,
} from './hooks/useFuzzySearch';
export {
  fuzzySearch,
  reRankWithFuse,
  calculateSimilarity,
  type FuzzySearchOptions,
  type FuzzySearchResult,
} from './utils/fuzzySearch';

// Entity ownership and deletion requests
export { useEntityOwnership } from './hooks/useEntityOwnership';
export { useDeletionRequest } from './hooks/useDeletionRequest';
