import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useTranslation } from 'react-i18next';
import { Search, Filter, Download, Trash2, Plus } from 'lucide-react';
import { Input } from '@/components/common/shadcn/input';
import { FmCommonButton } from '@/components/common/buttons/FmCommonButton';
export function FmDataGridToolbar({ searchQuery, onSearchChange, hasActiveFilters, onClearFilters, selectedCount, onBatchDelete, onBulkEdit, onExport, onGroupBy, onCreate, onCreateButtonClick, resourceName = 'Resource', createButtonLabel, enableExport = true, hasGrouping = false, totalDataCount, toolbarActions, isBatchDeleting = false, }) {
    const { t } = useTranslation('common');
    return (_jsxs("div", { className: 'flex items-center gap-4', children: [_jsxs("div", { className: 'relative flex-1', children: [_jsx(Search, { className: 'absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground' }), _jsx(Input, { placeholder: t('placeholders.searchAllColumns'), value: searchQuery, onChange: e => onSearchChange(e.target.value), className: 'pl-10 bg-background/50 border-border/50 focus:border-fm-gold transition-all duration-300' })] }), hasActiveFilters && (_jsx(FmCommonButton, { variant: 'default', size: 'sm', onClick: onClearFilters, className: 'animate-in fade-in duration-300', children: t('table.clearFilters') })), _jsxs("div", { className: 'ml-auto flex items-center gap-2', children: [_jsx("div", { className: 'text-sm text-muted-foreground', children: selectedCount > 0 && (_jsx("span", { className: 'animate-in fade-in slide-in-from-right duration-300', children: t('table.rowsSelected', { count: selectedCount }) })) }), selectedCount > 0 && onBatchDelete && (_jsx(FmCommonButton, { onClick: onBatchDelete, variant: 'destructive', size: 'sm', disabled: isBatchDeleting, icon: Trash2, className: 'animate-in fade-in slide-in-from-right duration-300', children: t('table.delete', { count: selectedCount }) })), selectedCount > 0 && onBulkEdit && (_jsx(FmCommonButton, { onClick: onBulkEdit, variant: 'default', size: 'sm', icon: Plus, className: 'animate-in fade-in slide-in-from-right duration-300', children: t('table.edit', { count: selectedCount }) })), enableExport && totalDataCount > 0 && onExport && (_jsx(FmCommonButton, { onClick: onExport, variant: 'default', size: 'sm', icon: Download, children: t('table.export') })), totalDataCount > 0 && onGroupBy && (_jsx(FmCommonButton, { onClick: onGroupBy, variant: 'default', size: 'sm', icon: Filter, children: hasGrouping ? t('table.grouped') : t('table.groupBy') })), toolbarActions, (onCreate || onCreateButtonClick) && (_jsx(FmCommonButton, { onClick: onCreateButtonClick || onCreate, variant: 'default', size: 'sm', icon: Plus, iconPosition: 'left', children: createButtonLabel || t('table.add', { resource: resourceName }) }))] })] }));
}
