import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useNavigate } from 'react-router-dom';
import { useTranslation } from 'react-i18next';
import { Dialog, DialogContent, DialogHeader, DialogTitle, } from '@/components/common/shadcn/dialog';
import { FmCommonCollapsibleSection } from '@/components/common/data/FmCommonCollapsibleSection';
import { ATTENDEE_PLACEHOLDERS } from './constants';
export function AttendeeModal({ open, onOpenChange, attendeeList, }) {
    const { t } = useTranslation('common');
    const navigate = useNavigate();
    return (_jsx(Dialog, { open: open, onOpenChange: onOpenChange, children: _jsxs(DialogContent, { className: 'max-w-md bg-background/95 backdrop-blur border border-border/60 max-h-[85vh] flex flex-col p-0 overflow-hidden', children: [_jsx(DialogHeader, { className: 'flex-shrink-0 px-6 pt-6 pb-4', children: _jsx(DialogTitle, { className: 'font-canela text-lg', children: t('guestList.guestListTitle') }) }), _jsxs("div", { className: 'flex-1 overflow-y-auto px-6 pb-6', children: [_jsx(FmCommonCollapsibleSection, { title: t('guestList.haveTickets'), defaultExpanded: true, className: 'mb-4', children: _jsx("div", { className: 'grid grid-cols-4 gap-3', children: attendeeList
                                    .slice(0, ATTENDEE_PLACEHOLDERS.length)
                                    .map((attendee, index) => (_jsxs("div", { className: 'flex flex-col items-center gap-2 text-center group cursor-pointer', onClick: () => navigate(`/profile/${attendee.avatar.toLowerCase()}`), children: [_jsx("div", { className: 'flex h-12 w-12 items-center justify-center rounded-full border-2 border-border bg-gradient-to-br from-fm-gold/15 to-fm-gold/35 text-xs font-semibold uppercase text-fm-gold transition-all duration-200 group-hover:scale-110 group-hover:border-fm-gold', children: attendee.avatar }), _jsx("span", { className: 'w-full truncate text-[11px] leading-tight text-muted-foreground', children: attendee.name })] }, `${attendee.avatar}-${index}`))) }) }), attendeeList.length > ATTENDEE_PLACEHOLDERS.length && (_jsxs(FmCommonCollapsibleSection, { title: t('guestList.privateGuests'), defaultExpanded: false, className: 'mb-4', children: [_jsx("div", { className: 'mb-3 flex items-center justify-end', children: _jsxs("span", { className: 'text-[10px] font-light text-muted-foreground/70', children: ["+", (attendeeList.length -
                                                ATTENDEE_PLACEHOLDERS.length -
                                                4).toLocaleString(), ' ', t('guestList.more')] }) }), _jsx("div", { className: 'grid grid-cols-4 gap-3', children: attendeeList
                                        .slice(ATTENDEE_PLACEHOLDERS.length, ATTENDEE_PLACEHOLDERS.length + 4)
                                        .map((attendee, index) => (_jsxs("div", { className: 'flex flex-col items-center gap-2 text-center', children: [_jsx("div", { className: 'flex h-12 w-12 items-center justify-center rounded-full border border-border bg-gradient-to-br from-fm-gold/15 to-fm-gold/35 text-xs font-semibold uppercase text-fm-gold blur-sm', children: attendee.avatar }), _jsx("span", { className: 'w-full truncate text-[11px] leading-tight text-muted-foreground blur-sm', children: attendee.name })] }, `private-${attendee.avatar}-${index}`))) })] })), _jsxs(FmCommonCollapsibleSection, { title: t('guestList.interested'), defaultExpanded: true, className: 'mb-4', children: [_jsx("div", { className: 'mb-3 flex items-center justify-end', children: attendeeList.length > 8 && (_jsxs("span", { className: 'text-[10px] font-light text-muted-foreground/70', children: ["+", Math.max(0, attendeeList.length - 8).toLocaleString(), ' ', t('guestList.more')] })) }), _jsx("div", { className: 'grid grid-cols-4 gap-3', children: attendeeList.slice(0, 8).map((attendee, index) => (_jsxs("div", { className: 'flex flex-col items-center gap-2 text-center group cursor-pointer', onClick: () => navigate(`/profile/${attendee.avatar.toLowerCase()}`), children: [_jsx("div", { className: 'flex h-12 w-12 items-center justify-center rounded-full border border-border bg-gradient-to-br from-muted-foreground/15 to-muted-foreground/35 text-xs font-semibold uppercase text-muted-foreground transition-all duration-200 group-hover:scale-110 group-hover:border-fm-gold group-hover:from-fm-gold/15 group-hover:to-fm-gold/35 group-hover:text-fm-gold', children: attendee.avatar }), _jsx("span", { className: 'w-full truncate text-[11px] leading-tight text-muted-foreground', children: attendee.name })] }, `interested-${attendee.avatar}-${index}`))) })] })] })] }) }));
}
