import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useTranslation } from 'react-i18next';
import { ChevronLeft } from 'lucide-react';
import { FmCommonTextField } from '@/components/common/forms/FmCommonTextField';
import { FmCommonButton } from '@/components/common/buttons/FmCommonButton';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue, } from '@/components/common/shadcn/select';
const PAID_SHOW_OPTIONS = [
    { value: '1-5', labelKey: 'paidShowsOptions.1-5' },
    { value: '6-15', labelKey: 'paidShowsOptions.6-15' },
    { value: '15-50', labelKey: 'paidShowsOptions.15-50' },
    { value: '50+', labelKey: 'paidShowsOptions.50+' },
];
export function PerformanceHistoryStep({ formData, onInputChange, onNext, onPrevious, }) {
    const { t } = useTranslation('common');
    return (_jsxs("div", { className: 'h-full flex flex-col p-[20px]', children: [_jsx("div", { className: 'flex-1 overflow-y-auto pr-[10px]', children: _jsx("div", { className: 'flex justify-center items-start', children: _jsxs("div", { className: 'w-[85vw] sm:w-[80%] space-y-[20px] bg-black/60 backdrop-blur-sm border border-white/10 p-[30px] sm:p-[40px]', children: [_jsxs("div", { children: [_jsx("h2", { className: 'font-canela text-3xl mb-[10px]', children: t('artistRegistration.performanceHistoryTitle') }), _jsx("p", { className: 'font-canela text-sm text-muted-foreground', children: t('artistRegistration.performanceHistoryDescription') })] }), _jsx("div", { className: 'w-full h-[1px] bg-gradient-to-r from-fm-gold via-white/30 to-transparent' }), _jsxs("div", { className: 'space-y-[20px]', children: [_jsxs("div", { className: 'space-y-[5px]', children: [_jsxs("label", { className: 'font-canela text-xs uppercase text-muted-foreground', children: [t('artistRegistration.paidShowsLabel'), " ", _jsx("span", { className: 'text-fm-danger', children: "*" })] }), _jsxs(Select, { value: formData.paidShowCountGroup, onValueChange: value => onInputChange('paidShowCountGroup', value), children: [_jsx(SelectTrigger, { className: 'w-full bg-transparent border border-white/20 hover:border-fm-gold/50 focus:border-fm-gold focus:border-b-[3px] focus:border-t-0 focus:border-l-0 focus:border-r-0 rounded-none font-canela transition-all duration-300', children: _jsx(SelectValue, { placeholder: t('artistRegistration.paidShowsPlaceholder') }) }), _jsx(SelectContent, { className: 'bg-black/95 backdrop-blur-md border border-white/20 rounded-none', children: PAID_SHOW_OPTIONS.map(option => (_jsx(SelectItem, { value: option.value, className: 'font-canela hover:bg-fm-gold/10 focus:bg-fm-gold/20 rounded-none cursor-pointer', children: t(`artistRegistration.${option.labelKey}`) }, option.value))) })] })] }), _jsx("div", { className: 'w-full h-[1px] bg-gradient-to-r from-transparent via-white/30 to-transparent' }), _jsx(FmCommonTextField, { label: t('artistRegistration.talentDifferentiatorLabel'), required: true, value: formData.talentDifferentiator, onChange: e => onInputChange('talentDifferentiator', e.target.value), placeholder: t('artistRegistration.talentDifferentiatorPlaceholder'), multiline: true, rows: 4 }), _jsx(FmCommonTextField, { label: t('artistRegistration.crowdSourcesLabel'), required: true, value: formData.crowdSources, onChange: e => onInputChange('crowdSources', e.target.value), placeholder: t('artistRegistration.crowdSourcesPlaceholder'), multiline: true, rows: 4 })] })] }) }) }), _jsxs("div", { className: 'flex justify-between pt-[20px] border-t border-white/10 flex-shrink-0', children: [_jsxs(FmCommonButton, { onClick: onPrevious, variant: 'secondary', children: [_jsx(ChevronLeft, { className: 'h-4 w-4 mr-[10px]' }), t('buttons.previous')] }), _jsx(FmCommonButton, { onClick: onNext, variant: 'default', children: t('buttons.next') })] })] }));
}
