import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { useTranslation } from 'react-i18next';
import { ExternalLink } from 'lucide-react';
import { DecorativeDivider } from '@/components/primitives/DecorativeDivider';
import { AnimatedCounter } from '@/components/primitives/AnimatedCounter';
import { MessagePanel } from '@/components/feedback/MessagePanel';
import { FmI18nCommon } from '@/components/common/i18n';
import { Button } from '@/components/common/shadcn/button';
import { LF_SYSTEM_TICKET_URL, PROMO_CODE, } from '@/shared';
export function PromoCodePanel({ userDisplayName, onJoinClick, onSignInClick, lowClaimLocationsCount, }) {
    const { t } = useTranslation('common');
    return (_jsx(MessagePanel, { title: '', description: '', action: _jsxs(_Fragment, { children: [_jsx(FmI18nCommon, { i18nKey: 'scavenger.promoCode.spotsClaimed', as: 'h1', className: 'font-display text-4xl md:text-5xl mb-4' }), _jsx(FmI18nCommon, { i18nKey: 'scavenger.promoCode.spotsClaimedDescription', as: 'p', className: 'text-base text-muted-foreground mb-4' }), _jsx(DecorativeDivider, {}), typeof lowClaimLocationsCount === 'number' && (_jsxs("p", { className: 'text-sm text-muted-foreground mb-4', children: [t('scavenger.promoCode.locationsAvailable'), ' ', _jsx(AnimatedCounter, { value: lowClaimLocationsCount, duration: 1200, className: 'inline text-fm-gold font-bold text-xl align-baseline mx-2' }), ' ', t('scavenger.promoCode.checkInstagram'), ' ', _jsx("span", { className: 'text-fm-gold font-semibold', children: "@force.majeure.events" }), ' ', t('scavenger.promoCode.forHints')] })), _jsx(DecorativeDivider, {}), userDisplayName ? (_jsxs(_Fragment, { children: [_jsx(FmI18nCommon, { i18nKey: 'scavenger.promoCode.yourPromoCode', as: 'h2', className: 'font-display text-2xl md:text-3xl text-fm-gold mb-4' }), _jsx("div", { className: 'bg-black/50 border-2 border-fm-gold p-4 rounded-lg mb-6', children: _jsx("code", { className: 'font-mono text-lg md:text-xl text-fm-gold tracking-wider', children: PROMO_CODE }) }), _jsxs(Button, { size: 'lg', className: 'w-full max-w-xs mx-auto bg-gradient-gold hover:opacity-90 font-semibold text-black transition-all duration-300 hover:scale-105 hover:shadow-[0_0_20px_rgba(212,175,55,0.4)]', onClick: () => window.open(LF_SYSTEM_TICKET_URL, '_blank'), children: [_jsx(ExternalLink, { className: 'mr-2 h-4 w-4' }), t('scavenger.promoCode.buyTicketsNow')] })] })) : (_jsxs(_Fragment, { children: [_jsx(Button, { size: 'lg', className: 'w-full max-w-xs mx-auto bg-gradient-gold hover:opacity-90 font-semibold text-black transition-all duration-300 hover:scale-105 hover:shadow-[0_0_20px_rgba(212,175,55,0.4)]', onClick: onJoinClick, children: t('scavenger.buttons.join') }), _jsx(Button, { size: 'lg', className: 'w-full max-w-xs mx-auto mt-4 bg-transparent border-2 border-white text-white hover:bg-white hover:text-black font-semibold transition-all duration-300 hover:scale-105 hover:shadow-[0_0_20px_rgba(255,255,255,0.4)]', onClick: onSignInClick, children: t('auth.signIn') })] }))] }) }));
}
