import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { LocationCard } from '../shared';
import { Footer } from '@/components/navigation/Footer';
import { ScavengerNavigation } from '@/components/navigation/ScavengerNavigation';
import { Card } from '@/components/common/shadcn/card';
import { TopographicBackground } from '@/components/common/misc/TopographicBackground';
export function ScavengerFullLayout({ showShoppingCart = true, locations = [], userClaims = [], children, }) {
    return (_jsxs(_Fragment, { children: [_jsx(ScavengerNavigation, { showShoppingCart: showShoppingCart }), _jsxs("div", { className: 'h-[calc(100vh-6.5rem)] flex flex-col lg:flex-row', children: [_jsxs("div", { className: 'flex-1 lg:w-1/2 flex items-start justify-center lg:overflow-y-auto relative z-10 lg:shadow-[8px_0_24px_-8px_rgba(0,0,0,0.3)] lg:border-r border-border', children: [_jsx(TopographicBackground, { opacity: 0.15, className: 'lg:opacity-[0.25] backdrop-blur-sm' }), _jsxs("div", { className: 'w-full max-w-3xl px-4 py-6 lg:px-8 lg:py-12 relative z-10', children: [_jsxs("div", { className: 'text-center mb-8', children: [_jsxs("h1", { className: 'font-display text-3xl md:text-4xl mb-4', children: [_jsx("span", { className: 'text-fm-gold', children: "LF System" }), " Scavenger Hunt"] }), _jsx("p", { className: 'text-lg text-muted-foreground', children: "Find all 5 locations to complete the hunt!" })] }), _jsxs("div", { className: 'space-y-6', children: [_jsx("div", { className: 'grid gap-4 md:grid-cols-2', children: locations?.map(location => (_jsx(LocationCard, { locationName: location.location_name, totalTokens: location.total_tokens, tokensRemaining: location.tokens_remaining }, location.id))) }), userClaims && userClaims.length > 0 && (_jsxs(Card, { className: 'p-4 bg-gradient-gold border-none text-primary-foreground', children: [_jsx("h3", { className: 'font-display text-xl mb-3', children: "Your Progress" }), _jsxs("div", { className: 'space-y-2', children: [_jsxs("p", { className: 'text-base', children: ["You've found", ' ', _jsx("span", { className: 'font-bold', children: userClaims.length }), " of 5 locations!"] }), _jsx("div", { className: 'space-y-1', children: userClaims.map(claim => (_jsxs("div", { className: 'flex items-center justify-between bg-primary-foreground/10 rounded-lg p-2', children: [_jsx("span", { className: 'font-medium text-sm', children: claim.scavenger_locations.location_name }), _jsxs("span", { className: 'text-xs', children: ["Position #", claim.claim_position] })] }, claim.id))) })] })] })), children] })] })] }), _jsx("div", { className: 'hidden lg:block lg:w-1/2 bg-muted relative overflow-hidden', children: _jsx(TopographicBackground, { opacity: 0.4 }) })] }), _jsx(Footer, {})] }));
}
