import { jsxs as _jsxs, jsx as _jsx } from "react/jsx-runtime";
import { FmCommonLoadingSpinner } from '@/components/common/feedback/FmCommonLoadingSpinner';
import { Badge } from '@/components/common/shadcn/badge';
import { Clock, CheckCircle2 } from 'lucide-react';
import { formatDistanceToNow } from 'date-fns';
export function TestThreadMonitor({ activeThreads, maxConcurrency, queuedCount, }) {
    const completedThreads = activeThreads.filter(t => t.status === 'completed');
    const runningThreads = activeThreads.filter(t => t.status === 'active');
    return (_jsxs("div", { className: 'space-y-4', children: [_jsxs("div", { className: 'flex items-center gap-4', children: [_jsxs("div", { className: 'flex items-center gap-2', children: [_jsxs(Badge, { variant: 'default', className: 'bg-fm-gold/20 text-fm-gold border-fm-gold/30', children: [runningThreads.length, " / ", maxConcurrency] }), _jsx("span", { className: 'text-sm text-muted-foreground', children: "Active Threads" })] }), queuedCount > 0 && (_jsxs("div", { className: 'flex items-center gap-2', children: [_jsx(Badge, { variant: 'outline', children: queuedCount }), _jsx("span", { className: 'text-sm text-muted-foreground', children: "Queued" })] }))] }), runningThreads.length > 0 && (_jsxs("div", { className: 'space-y-2', children: [_jsx("h4", { className: 'text-sm font-medium text-muted-foreground', children: "Running Tests" }), _jsx("div", { className: 'space-y-2', children: runningThreads.map(thread => (_jsxs("div", { className: 'flex items-center gap-3 p-3 bg-card border border-border rounded-lg', children: [_jsx(FmCommonLoadingSpinner, { size: 'sm' }), _jsxs("div", { className: 'flex-1 min-w-0', children: [_jsx("p", { className: 'text-sm font-medium truncate', children: thread.testName }), _jsxs("div", { className: 'flex items-center gap-2 text-xs text-muted-foreground mt-1', children: [_jsx(Clock, { className: 'h-3 w-3' }), _jsxs("span", { children: ["Started", ' ', formatDistanceToNow(thread.startTime, {
                                                            addSuffix: true,
                                                        })] })] })] })] }, thread.threadId))) })] })), completedThreads.length > 0 && (_jsxs("div", { className: 'space-y-2', children: [_jsx("h4", { className: 'text-sm font-medium text-muted-foreground', children: "Recently Completed" }), _jsx("div", { className: 'space-y-2', children: completedThreads.slice(0, 3).map(thread => (_jsxs("div", { className: 'flex items-center gap-3 p-3 bg-card border border-border rounded-lg opacity-50', children: [_jsx(CheckCircle2, { className: 'h-4 w-4 text-green-500' }), _jsx("div", { className: 'flex-1 min-w-0', children: _jsx("p", { className: 'text-sm font-medium truncate', children: thread.testName }) })] }, thread.threadId))) })] }))] }));
}
