import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { format } from 'date-fns';
import { useTranslation } from 'react-i18next';
import { Label } from '@/components/common/shadcn/label';
import { Checkbox } from '@/components/common/shadcn/checkbox';
import { FmArtistSearchDropdown } from '@/components/common/search/FmArtistSearchDropdown';
import { FmVenueSearchDropdown } from '@/components/common/search/FmVenueSearchDropdown';
import { FmCommonDatePicker } from '@/components/common/forms/FmCommonDatePicker';
import { FmCommonTimePicker } from '@/components/common/forms/FmCommonTimePicker';
import { FmFlexibleImageUpload } from '@/components/common/forms/FmFlexibleImageUpload';
/**
 * EventDetailsFormSection
 *
 * Shared form section for event details (headliner, date/time, venue, hero image).
 * Used by both FmCreateEventButton and FmEditEventButton.
 */
export function EventDetailsFormSection({ state, actions, onImageUploadStateChange }) {
    const { t } = useTranslation('common');
    return (_jsxs("div", { className: 'space-y-4', children: [_jsxs("div", { className: 'space-y-2', children: [_jsxs(Label, { className: 'text-white', children: [t('formLabels.eventTitle'), " ", _jsx("span", { className: 'text-fm-danger', children: "*" })] }), _jsx("input", { type: 'text', value: state.title, onChange: e => actions.setTitle(e.target.value), placeholder: t('forms.events.titlePlaceholder'), className: 'w-full px-3 py-2 bg-white/5 border border-white/20 rounded-md text-white placeholder:text-white/50 focus:outline-none focus:ring-2 focus:ring-fm-gold/50' })] }), _jsxs("div", { className: 'space-y-2', children: [_jsx(Label, { className: 'text-white', children: t('formLabels.subtitleOptional') }), _jsx("input", { type: 'text', value: state.subtitle, onChange: e => actions.setSubtitle(e.target.value), placeholder: t('forms.events.subtitlePlaceholder'), className: 'w-full px-3 py-2 bg-white/5 border border-white/20 rounded-md text-white placeholder:text-white/50 focus:outline-none focus:ring-2 focus:ring-fm-gold/50' })] }), _jsxs("div", { className: 'space-y-2', children: [_jsxs(Label, { className: 'text-white', children: [t('formLabels.headliner'), " ", _jsx("span", { className: 'text-fm-danger', children: "*" })] }), _jsx(FmArtistSearchDropdown, { value: state.headlinerId, onChange: actions.setHeadlinerId, placeholder: t('forms.events.searchHeadliner') })] }), _jsxs("div", { className: 'space-y-2', children: [_jsxs(Label, { className: 'text-white', children: [t('formLabels.date'), " ", _jsx("span", { className: 'text-fm-danger', children: "*" })] }), _jsx(FmCommonDatePicker, { value: state.eventDate, onChange: actions.setEventDate, placeholder: t('forms.events.selectEventDate') })] }), _jsxs("div", { className: 'grid grid-cols-2 gap-4', children: [_jsxs("div", { className: 'space-y-2', children: [_jsxs(Label, { className: 'text-white', children: [t('formLabels.startTime'), " ", _jsx("span", { className: 'text-fm-danger', children: "*" })] }), _jsx(FmCommonTimePicker, { value: state.eventDate ? format(state.eventDate, 'HH:mm') : '20:00', onChange: time => {
                                    if (state.eventDate) {
                                        const [hours, minutes] = time.split(':');
                                        const newDate = new Date(state.eventDate);
                                        newDate.setHours(parseInt(hours, 10), parseInt(minutes, 10));
                                        actions.setEventDate(newDate);
                                    }
                                }, placeholder: t('forms.events.selectStartTime') })] }), _jsxs("div", { className: 'space-y-2', children: [_jsxs(Label, { className: 'text-white', children: [t('formLabels.endTime'), " ", _jsx("span", { className: 'text-fm-danger', children: "*" })] }), _jsx(FmCommonTimePicker, { value: state.endTime, onChange: actions.setEndTime, disabled: state.isAfterHours, placeholder: t('forms.events.selectEndTime') })] })] }), _jsxs("div", { className: 'space-y-1', children: [_jsxs("div", { className: 'flex items-center gap-2', children: [_jsx(Checkbox, { id: 'after-hours', checked: state.isAfterHours, onCheckedChange: checked => actions.setIsAfterHours(checked === true) }), _jsx(Label, { htmlFor: 'after-hours', className: 'text-white/70 cursor-pointer', children: t('formLabels.afterHoursEvent') })] }), _jsx("p", { className: 'text-xs text-white/50 ml-6', children: t('formLabels.afterHoursHelp') })] }), _jsxs("div", { className: 'space-y-1', children: [_jsxs("div", { className: 'flex items-center gap-2', children: [_jsx(Checkbox, { id: 'tba-event', checked: state.isTba, onCheckedChange: checked => actions.setIsTba(checked === true) }), _jsx(Label, { htmlFor: 'tba-event', className: 'text-white/70 cursor-pointer', children: t('formLabels.tbaEvent') })] }), _jsx("p", { className: 'text-xs text-white/50 ml-6', children: t('formLabels.tbaEventHelp') })] }), _jsxs("div", { className: 'space-y-2', children: [_jsxs(Label, { className: 'text-white', children: [t('formLabels.venue'), " ", _jsx("span", { className: 'text-fm-danger', children: "*" })] }), _jsx(FmVenueSearchDropdown, { value: state.venueId, onChange: actions.setVenueId, placeholder: t('placeholders.searchVenue') })] }), _jsx("div", { className: 'space-y-2', children: _jsx(FmFlexibleImageUpload, { label: t('formLabels.mainEventImage'), value: state.heroImage, onChange: actions.setHeroImage, bucket: 'event-images', pathPrefix: 'events', onUploadStateChange: onImageUploadStateChange }) })] }));
}
